# Generated by Django 6.0.8 on 2026-08-21 15:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trilhas', '0015_videonivel_etapa_videonivel_iniciado_em'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('subtopico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversas', to='trilhas.subtopico')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'conversa',
                'verbose_name_plural': 'conversas',
                'ordering': ['-atualizada_em'],
            },
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papel', models.CharField(choices=[('aluno', 'Aluno'), ('ia', 'IA')], max_length=6)),
                ('texto', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('gerando', 'Gerando'), ('pronta', 'Pronta'), ('recusada', 'Fora de escopo'), ('erro', 'Erro')], db_index=True, default='pronta', max_length=10)),
                ('erro', models.TextField(blank=True)),
                ('tokens_entrada', models.PositiveIntegerField(default=0)),
                ('tokens_saida', models.PositiveIntegerField(default=0)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('conversa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='chat.conversa')),
            ],
            options={
                'verbose_name': 'mensagem',
                'verbose_name_plural': 'mensagens',
                'ordering': ['criada_em', 'pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='conversa',
            constraint=models.UniqueConstraint(condition=models.Q(('subtopico__isnull', False)), fields=('user', 'subtopico'), name='conversa_unica_por_subtopico'),
        ),
        migrations.AddConstraint(
            model_name='conversa',
            constraint=models.UniqueConstraint(condition=models.Q(('subtopico__isnull', True)), fields=('user',), name='conversa_geral_unica'),
        ),
    ]
