# Generated by Django 6.0.8 on 2026-08-21 16:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def mudar_a_conversa_de_topico_para_trilha(apps, schema_editor):
    """Reancora as conversas existentes: cada uma passa a ser da trilha do seu
    subtópico, e as mensagens guardam de qual página a pergunta saiu.

    Se o aluno tinha conversas em tópicos diferentes da MESMA trilha, elas viram
    uma só — a restrição nova é por (aluno, trilha). As falas são costuradas na
    conversa mais recente, em ordem de criação; nenhuma pergunta se perde.
    """
    Conversa = apps.get_model("chat", "Conversa")
    Mensagem = apps.get_model("chat", "Mensagem")

    conversas = Conversa.objects.exclude(subtopico=None).select_related(
        "subtopico__nivel"
    ).order_by("-atualizada_em")

    destino_da_trilha = {}
    for conversa in conversas:
        trilha_id = conversa.subtopico.nivel.trilha_id
        Mensagem.objects.filter(conversa=conversa).update(subtopico=conversa.subtopico_id)

        chave = (conversa.user_id, trilha_id)
        destino = destino_da_trilha.get(chave)
        if destino is None:
            # A primeira da fila é a mais recente: ela fica e recebe as outras.
            destino_da_trilha[chave] = conversa.pk
            conversa.trilha_id = trilha_id
            conversa.save(update_fields=["trilha"])
        else:
            Mensagem.objects.filter(conversa=conversa).update(conversa_id=destino)
            conversa.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        ('trilhas', '0015_videonivel_etapa_videonivel_iniciado_em'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='conversa',
            name='conversa_unica_por_subtopico',
        ),
        migrations.RemoveConstraint(
            model_name='conversa',
            name='conversa_geral_unica',
        ),
        migrations.AddField(
            model_name='conversa',
            name='trilha',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversas', to='trilhas.trilha'),
        ),
        migrations.AddField(
            model_name='mensagem',
            name='subtopico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensagens_chat', to='trilhas.subtopico'),
        ),
        # Antes das restrições novas e da remoção do campo antigo: é a última
        # janela em que dá para ler o subtópico da conversa.
        migrations.RunPython(
            mudar_a_conversa_de_topico_para_trilha, migrations.RunPython.noop
        ),
        migrations.AddConstraint(
            model_name='conversa',
            constraint=models.UniqueConstraint(condition=models.Q(('trilha__isnull', False)), fields=('user', 'trilha'), name='conversa_unica_por_trilha'),
        ),
        migrations.AddConstraint(
            model_name='conversa',
            constraint=models.UniqueConstraint(condition=models.Q(('trilha__isnull', True)), fields=('user',), name='conversa_geral_unica'),
        ),
        migrations.RemoveField(
            model_name='conversa',
            name='subtopico',
        ),
    ]
