# Generated by Django 6.0.6 on 2026-07-03 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trilhas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tentativa', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('gerando', 'Gerando'), ('pronta', 'Pronta'), ('corrigindo', 'Corrigindo'), ('corrigida', 'Corrigida'), ('erro', 'Erro')], db_index=True, default='gerando', max_length=15)),
                ('nota_final', models.FloatField(blank=True, null=True)),
                ('aprovado', models.BooleanField(default=False)),
                ('feedback_geral', models.TextField(blank=True)),
                ('erro', models.TextField(blank=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('corrigida_em', models.DateTimeField(blank=True, null=True)),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='trilhas.nivel')),
            ],
            options={
                'verbose_name': 'avaliação',
                'verbose_name_plural': 'avaliações',
                'ordering': ['-criada_em'],
            },
        ),
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('tipo', models.CharField(choices=[('objetiva', 'Objetiva'), ('dissertativa', 'Dissertativa')], max_length=15)),
                ('enunciado_md', models.TextField()),
                ('alternativas', models.JSONField(blank=True, default=list)),
                ('gabarito', models.TextField(blank=True)),
                ('peso', models.FloatField(default=1.0)),
                ('avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questoes', to='avaliacoes.avaliacao')),
            ],
            options={
                'verbose_name': 'questão',
                'verbose_name_plural': 'questões',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alternativa_escolhida', models.CharField(blank=True, max_length=5)),
                ('resposta_texto', models.TextField(blank=True)),
                ('nota', models.FloatField(blank=True, null=True)),
                ('feedback_md', models.TextField(blank=True)),
                ('corrigida_em', models.DateTimeField(blank=True, null=True)),
                ('questao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resposta', to='avaliacoes.questao')),
            ],
            options={
                'verbose_name': 'resposta',
                'verbose_name_plural': 'respostas',
            },
        ),
        migrations.CreateModel(
            name='Titulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('faixa', models.CharField(max_length=15)),
                ('concedido_em', models.DateTimeField(auto_now_add=True)),
                ('nivel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='titulo_conquistado', to='trilhas.nivel')),
                ('trilha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='titulos', to='trilhas.trilha')),
            ],
            options={
                'verbose_name': 'título',
                'verbose_name_plural': 'títulos',
                'ordering': ['concedido_em'],
            },
        ),
    ]
