# Generated by Django 6.0.6 on 2026-07-04 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0001_initial'),
        ('trilhas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaExercicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('gerando', 'Gerando'), ('pronta', 'Pronta'), ('erro', 'Erro')], db_index=True, default='gerando', max_length=15)),
                ('erro', models.TextField(blank=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('nivel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lista_exercicios', to='trilhas.nivel')),
            ],
            options={
                'verbose_name': 'lista de exercícios',
                'verbose_name_plural': 'listas de exercícios',
            },
        ),
        migrations.CreateModel(
            name='Exercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('tipo', models.CharField(choices=[('objetiva', 'Objetiva'), ('dissertativa', 'Dissertativa')], max_length=15)),
                ('enunciado_md', models.TextField()),
                ('alternativas', models.JSONField(blank=True, default=list)),
                ('gabarito', models.TextField(blank=True)),
                ('explicacao_md', models.TextField(blank=True)),
                ('resposta_texto', models.TextField(blank=True)),
                ('alternativa_escolhida', models.CharField(blank=True, max_length=5)),
                ('nota', models.FloatField(blank=True, null=True)),
                ('feedback_md', models.TextField(blank=True)),
                ('respondido_em', models.DateTimeField(blank=True, null=True)),
                ('lista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercicios', to='avaliacoes.listaexercicios')),
            ],
            options={
                'verbose_name': 'exercício',
                'verbose_name_plural': 'exercícios',
                'ordering': ['ordem'],
            },
        ),
    ]
