# Generated by Django 6.0.6 on 2026-07-04 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0002_listaexercicios_exercicio'),
        ('trilhas', '0004_trilha_categoria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Revisao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('gerando', 'Gerando'), ('pronta', 'Pronta'), ('erro', 'Erro')], db_index=True, default='gerando', max_length=15)),
                ('erro', models.TextField(blank=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'revisão',
                'verbose_name_plural': 'revisões',
                'ordering': ['-criada_em'],
            },
        ),
        migrations.CreateModel(
            name='QuestaoRevisao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('origem', models.CharField(blank=True, max_length=200)),
                ('enunciado_md', models.TextField()),
                ('alternativas', models.JSONField(blank=True, default=list)),
                ('gabarito', models.TextField(blank=True)),
                ('explicacao_md', models.TextField(blank=True)),
                ('alternativa_escolhida', models.CharField(blank=True, max_length=5)),
                ('nota', models.FloatField(blank=True, null=True)),
                ('respondido_em', models.DateTimeField(blank=True, null=True)),
                ('nivel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='trilhas.nivel')),
                ('revisao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questoes', to='avaliacoes.revisao')),
            ],
            options={
                'verbose_name': 'questão de revisão',
                'verbose_name_plural': 'questões de revisão',
                'ordering': ['ordem'],
            },
        ),
    ]
