# Generated by Django 6.0.6 on 2026-07-04 22:57

from django.db import migrations, models


def remover_dissertativas(apps, schema_editor):
    """Apaga as questões/exercícios dissertativos legados (cascade nas respostas)
    antes de derrubar as colunas de texto. Só há linhas em avaliações antigas."""
    Questao = apps.get_model('avaliacoes', 'Questao')
    Exercicio = apps.get_model('avaliacoes', 'Exercicio')
    Questao.objects.filter(tipo='dissertativa').delete()
    Exercicio.objects.filter(tipo='dissertativa').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0003_revisao_questaorevisao'),
    ]

    operations = [
        migrations.RunPython(remover_dissertativas, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='exercicio',
            name='resposta_texto',
        ),
        migrations.RemoveField(
            model_name='resposta',
            name='resposta_texto',
        ),
        migrations.AlterField(
            model_name='exercicio',
            name='tipo',
            field=models.CharField(choices=[('objetiva', 'Objetiva')], max_length=15),
        ),
        migrations.AlterField(
            model_name='questao',
            name='tipo',
            field=models.CharField(choices=[('objetiva', 'Objetiva')], max_length=15),
        ),
    ]
