# Generated by Django 6.0.8 on 2026-08-26 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0004_remove_exercicio_resposta_texto_and_more'),
        ('trilhas', '0015_videonivel_etapa_videonivel_iniciado_em'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerguntaRetrieval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('pronta', 'Pronta'), ('erro', 'Erro')], db_index=True, default='pendente', max_length=10)),
                ('enunciado_md', models.TextField(blank=True)),
                ('alternativas', models.JSONField(default=list)),
                ('gabarito', models.CharField(blank=True, max_length=1)),
                ('explicacao_md', models.TextField(blank=True)),
                ('erro', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('alternativa_escolhida', models.CharField(blank=True, max_length=1)),
                ('respondido_em', models.DateTimeField(blank=True, null=True)),
                ('subtopico', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pergunta_retrieval', to='trilhas.subtopico')),
            ],
            options={
                'verbose_name': 'pergunta de retrieval',
                'verbose_name_plural': 'perguntas de retrieval',
            },
        ),
    ]
