# Generated by Django 6.0.6 on 2026-07-03 22:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_visitor', models.BooleanField(default=False, verbose_name='é visitante')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='expira em')),
                ('tokens_usados_mes', models.BigIntegerField(default=0, verbose_name='tokens usados no mês')),
                ('quota_tokens_mes', models.BigIntegerField(default=0, verbose_name='quota mensal de tokens')),
                ('quota_ref', models.DateField(default=django.utils.timezone.localdate, verbose_name='mês de referência da quota')),
                ('custo_acumulado', models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='custo acumulado (USD)')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'perfil',
                'verbose_name_plural': 'perfis',
            },
        ),
    ]
