# Generated by Django 6.0.6 on 2026-07-04 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='streak_dias',
            field=models.PositiveIntegerField(default=0, verbose_name='sequência de dias'),
        ),
        migrations.AddField(
            model_name='profile',
            name='ultimo_estudo',
            field=models.DateField(blank=True, null=True, verbose_name='último dia de estudo'),
        ),
        migrations.AddField(
            model_name='profile',
            name='xp',
            field=models.BigIntegerField(default=0, verbose_name='XP'),
        ),
    ]
