# Generated by Django 6.0.6 on 2026-07-04 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_streak_dias_profile_ultimo_estudo_profile_xp'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='lembrete_streak_em',
            field=models.DateField(blank=True, null=True, verbose_name='último lembrete de ofensiva enviado em'),
        ),
    ]
