# Generated by Django 6.0.6 on 2026-07-28 19:50

from django.db import migrations, models


def backfill_creditados(apps, schema_editor):
    """Perfis existentes começam com os 3 diamantes-base; marca o XP já
    acumulado como creditado para não gerar uma enxurrada retroativa de
    diamantes no próximo ganho de XP."""
    Profile = apps.get_model('accounts', 'Profile')
    XP_POR_DIAMANTE = 1000
    for p in Profile.objects.all().iterator():
        creditados = int(p.xp or 0) // XP_POR_DIAMANTE
        if creditados:
            p.diamantes_xp_creditados = creditados
            p.save(update_fields=['diamantes_xp_creditados'])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_xp_diario_semana'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='diamantes',
            field=models.IntegerField(default=3, verbose_name='diamantes'),
        ),
        migrations.AddField(
            model_name='profile',
            name='diamantes_xp_creditados',
            field=models.IntegerField(default=0, verbose_name='diamantes creditados por XP'),
        ),
        migrations.RunPython(backfill_creditados, migrations.RunPython.noop),
    ]
