# Generated by Django 6.0.6 on 2026-07-29 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_diamantes_profile_diamantes_xp_creditados'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='diamantes_nivel_creditados',
            field=models.IntegerField(default=0, verbose_name='diamantes creditados por nível'),
        ),
    ]
