# Generated by Django 6.0.8 on 2026-08-21 15:32

from django.conf import settings
from django.db import migrations, models


def conceder_quota_de_chat(apps, schema_editor):
    """Sem isto, quem já tinha conta ficaria com o balde do chat zerado.

    Visitante recebe o balde reduzido; os demais, o padrão. Perfil que já tenha
    valor definido não é tocado (a migração pode rodar de novo num restore).
    """
    Profile = apps.get_model("accounts", "Profile")
    Profile.objects.filter(chat_quota_tokens_mes=0, is_visitor=True).update(
        chat_quota_tokens_mes=getattr(settings, "QUOTA_CHAT_TOKENS_VISITOR", 40_000)
    )
    Profile.objects.filter(chat_quota_tokens_mes=0, is_visitor=False).update(
        chat_quota_tokens_mes=getattr(settings, "QUOTA_CHAT_TOKENS_DEFAULT", 400_000)
    )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_diamantes_nivel_creditados'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='chat_quota_tokens_mes',
            field=models.BigIntegerField(default=0, verbose_name='quota mensal do chat'),
        ),
        migrations.AddField(
            model_name='profile',
            name='chat_tokens_usados_mes',
            field=models.BigIntegerField(default=0, verbose_name='tokens do chat no mês'),
        ),
        migrations.RunPython(conceder_quota_de_chat, migrations.RunPython.noop),
    ]
