# Generated by Django 6.0.6 on 2026-07-03 22:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('titulo', models.CharField(max_length=200)),
                ('resumo', models.TextField(blank=True)),
                ('faixa', models.CharField(choices=[('iniciante', 'Iniciante'), ('intermediario', 'Intermediário'), ('avancado', 'Avançado'), ('especialista', 'Especialista'), ('mestre', 'Mestre')], default='iniciante', max_length=15)),
                ('titulo_concedido', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('bloqueado', 'Bloqueado'), ('disponivel', 'Disponível'), ('conteudo_gerando', 'Gerando conteúdo'), ('conteudo_pronto', 'Conteúdo pronto'), ('aprovado', 'Aprovado'), ('erro', 'Erro')], db_index=True, default='bloqueado', max_length=20)),
                ('conteudo_md', models.TextField(blank=True, verbose_name='conteúdo (Markdown)')),
                ('erro', models.TextField(blank=True)),
                ('gerado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'nível',
                'verbose_name_plural': 'níveis',
                'ordering': ['trilha', 'ordem'],
            },
        ),
        migrations.CreateModel(
            name='Subtopico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('titulo', models.CharField(max_length=200)),
                ('descricao_curta', models.TextField(blank=True)),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtopicos', to='trilhas.nivel')),
            ],
            options={
                'verbose_name': 'subtópico',
                'verbose_name_plural': 'subtópicos',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='Trilha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema_livre', models.TextField(verbose_name='tema (descrição livre)')),
                ('titulo', models.CharField(blank=True, max_length=200, verbose_name='título')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('objetivos', models.JSONField(blank=True, default=list, verbose_name='objetivos de aprendizagem')),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('gerando_perguntas', 'Gerando perguntas'), ('aguardando_respostas', 'Aguardando respostas'), ('gerando_sumario', 'Gerando sumário'), ('sumario_gerado', 'Sumário gerado'), ('em_andamento', 'Em andamento'), ('concluida', 'Concluída'), ('erro', 'Erro')], db_index=True, default='rascunho', max_length=25)),
                ('nota_minima_aprovacao', models.FloatField(default=7.0, verbose_name='nota mínima de aprovação')),
                ('erro', models.TextField(blank=True, verbose_name='mensagem de erro')),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trilhas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'trilha',
                'verbose_name_plural': 'trilhas',
                'ordering': ['-criada_em'],
            },
        ),
        migrations.CreateModel(
            name='PerguntaDirecionadora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('pergunta', models.TextField()),
                ('tipo', models.CharField(choices=[('aberta', 'Aberta'), ('escolha_unica', 'Escolha única')], default='aberta', max_length=15)),
                ('opcoes', models.JSONField(blank=True, default=list)),
                ('resposta', models.TextField(blank=True)),
                ('trilha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perguntas', to='trilhas.trilha')),
            ],
            options={
                'verbose_name': 'pergunta direcionadora',
                'verbose_name_plural': 'perguntas direcionadoras',
                'ordering': ['ordem'],
            },
        ),
        migrations.AddField(
            model_name='nivel',
            name='trilha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='niveis', to='trilhas.trilha'),
        ),
    ]
