# Generated by Django 6.0.6 on 2026-07-04 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trilhas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtopico',
            name='conteudo_md',
            field=models.TextField(blank=True, verbose_name='conteúdo (Markdown)'),
        ),
        migrations.AddField(
            model_name='subtopico',
            name='erro',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='subtopico',
            name='gerado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subtopico',
            name='lido',
            field=models.BooleanField(default=False, verbose_name='lido'),
        ),
        migrations.AddField(
            model_name='subtopico',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('gerando', 'Gerando'), ('pronto', 'Pronto'), ('erro', 'Erro')], db_index=True, default='pendente', max_length=15),
        ),
    ]
