# Generated by Django 6.0.6 on 2026-07-04 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trilhas', '0002_subtopico_conteudo_md_subtopico_erro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trilha',
            name='emblema',
            field=models.CharField(blank=True, max_length=8, verbose_name='emblema (emoji)'),
        ),
    ]
