# Generated by Django 6.0.6 on 2026-07-04 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trilhas', '0003_trilha_emblema'),
    ]

    operations = [
        migrations.AddField(
            model_name='trilha',
            name='categoria',
            field=models.CharField(blank=True, db_index=True, max_length=60, verbose_name='categoria'),
        ),
    ]
