# Generated by Django 6.0.6 on 2026-07-04 13:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trilhas', '0004_trilha_categoria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Percurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('gerando', 'Gerando'), ('pronto', 'Pronto'), ('erro', 'Erro')], db_index=True, default='gerando', max_length=15)),
                ('resumo', models.TextField(blank=True, verbose_name='recado do mentor')),
                ('erro', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='percursos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'percurso',
                'verbose_name_plural': 'percursos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='PassoPercurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('tipo', models.CharField(choices=[('aprender', 'Aprender'), ('revisar', 'Revisar'), ('avaliar', 'Avaliar'), ('revisar_global', 'Revisão geral')], max_length=15)),
                ('titulo', models.CharField(max_length=200)),
                ('motivo', models.TextField(blank=True)),
                ('subtopico_ordem', models.PositiveIntegerField(blank=True, null=True)),
                ('nivel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='trilhas.nivel')),
                ('percurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passos', to='trilhas.percurso')),
            ],
            options={
                'verbose_name': 'passo do percurso',
                'verbose_name_plural': 'passos do percurso',
                'ordering': ['ordem'],
            },
        ),
    ]
