# Generated by Django 6.0.6 on 2026-07-04 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trilhas', '0005_percurso_passopercurso'),
    ]

    operations = [
        migrations.AddField(
            model_name='trilha',
            name='ativa',
            field=models.BooleanField(db_index=True, default=True, verbose_name='ativa'),
        ),
    ]
