# Generated by Django 6.0.6 on 2026-07-04 22:38

from django.db import migrations, models


def agendar_aprovados(apps, schema_editor):
    """Níveis já aprovados passam a ficar 'devidos' para revisão hoje."""
    from datetime import date
    Nivel = apps.get_model('trilhas', 'Nivel')
    Nivel.objects.filter(status='aprovado', revisao_proxima__isnull=True).update(
        revisao_ef=2.5, revisao_intervalo=1, revisao_repeticoes=0,
        revisao_proxima=date.today(),
    )


class Migration(migrations.Migration):

    dependencies = [
        ('trilhas', '0006_trilha_ativa'),
    ]

    operations = [
        migrations.AddField(
            model_name='nivel',
            name='revisao_ef',
            field=models.FloatField(default=2.5, verbose_name='fator de facilidade (SM-2)'),
        ),
        migrations.AddField(
            model_name='nivel',
            name='revisao_intervalo',
            field=models.PositiveIntegerField(default=0, verbose_name='intervalo de revisão (dias)'),
        ),
        migrations.AddField(
            model_name='nivel',
            name='revisao_proxima',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='próxima revisão'),
        ),
        migrations.AddField(
            model_name='nivel',
            name='revisao_repeticoes',
            field=models.PositiveIntegerField(default=0, verbose_name='repetições de revisão'),
        ),
        migrations.AddField(
            model_name='nivel',
            name='revisao_ultima',
            field=models.DateField(blank=True, null=True, verbose_name='última revisão'),
        ),
        migrations.RunPython(agendar_aprovados, migrations.RunPython.noop),
    ]
