# Generated by Django 6.0.6 on 2026-07-05 04:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trilhas', '0007_nivel_revisao_ef_nivel_revisao_intervalo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CardSalvo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indice', models.PositiveIntegerField(verbose_name='índice do card no tópico')),
                ('html', models.TextField(verbose_name='conteúdo do card (HTML)')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('subtopico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards_salvos', to='trilhas.subtopico')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards_salvos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'card salvo',
                'verbose_name_plural': 'cards salvos',
                'ordering': ['-criado_em'],
                'constraints': [models.UniqueConstraint(fields=('user', 'subtopico', 'indice'), name='card_salvo_unico')],
            },
        ),
    ]
