# Generated by Django 6.0.6 on 2026-07-06 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trilhas', '0008_cardsalvo'),
    ]

    operations = [
        migrations.AddField(
            model_name='trilha',
            name='cover_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='imagem de capa'),
        ),
    ]
