# Generated by Django 6.0.6 on 2026-07-10 13:30
import re

from django.db import migrations, models

_FOTO_ID_RE = re.compile(r'/photos/(\d+)/')


def _backfill_pexels_id(apps, schema_editor):
    """Preenche cover_pexels_id a partir das capas Pexels ainda hotlinkadas,
    para a deduplicação de fotos seguir funcionando nas trilhas antigas."""
    Trilha = apps.get_model('trilhas', 'Trilha')
    for t in Trilha.objects.exclude(cover_url=''):
        m = _FOTO_ID_RE.search(t.cover_url or '')
        if m:
            t.cover_pexels_id = int(m.group(1))
            t.save(update_fields=['cover_pexels_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('trilhas', '0009_cover_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='trilha',
            name='cover_pexels_id',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='foto Pexels (id)'),
        ),
        migrations.RunPython(_backfill_pexels_id, migrations.RunPython.noop),
    ]
