# Generated by Django 6.0.6 on 2026-07-22 02:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trilhas', '0010_trilha_cover_pexels_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SessaoSugestao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('gerando', 'Gerando'), ('pronto', 'Pronto'), ('erro', 'Erro')], db_index=True, default='gerando', max_length=15)),
                ('erro', models.TextField(blank=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('trilhas_base', models.ManyToManyField(blank=True, related_name='+', to='trilhas.trilha')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessoes_sugestao', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'sessão de sugestões',
                'verbose_name_plural': 'sessões de sugestões',
                'ordering': ['-criada_em'],
            },
        ),
        migrations.CreateModel(
            name='TrilhaSugerida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('tipo', models.CharField(choices=[('aprofundar', 'Aprofundar'), ('direcao', 'Nova direção')], default='direcao', max_length=12)),
                ('titulo', models.CharField(max_length=200)),
                ('enfoque', models.TextField(blank=True, verbose_name='enfoque')),
                ('topicos', models.JSONField(blank=True, default=list, verbose_name='principais tópicos')),
                ('sessao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sugestoes', to='trilhas.sessaosugestao')),
                ('trilha', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='trilhas.trilha')),
            ],
            options={
                'verbose_name': 'trilha sugerida',
                'verbose_name_plural': 'trilhas sugeridas',
                'ordering': ['ordem'],
            },
        ),
    ]
