# Generated by Django 6.0.6 on 2026-07-24 01:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trilhas', '0011_sessaosugestao_trilhasugerida'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoSubtopico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('gerando', 'Gerando'), ('pronto', 'Pronto'), ('erro', 'Erro')], db_index=True, default='pendente', max_length=15)),
                ('progresso_pct', models.PositiveIntegerField(default=0, verbose_name='progresso (%)')),
                ('arquivo', models.CharField(blank=True, max_length=300, verbose_name='arquivo (URL local)')),
                ('duracao_seg', models.PositiveIntegerField(default=0, verbose_name='duração (s)')),
                ('fonte_gerado_em', models.DateTimeField(blank=True, null=True)),
                ('erro', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('subtopico', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='video', to='trilhas.subtopico')),
            ],
            options={
                'verbose_name': 'vídeo de subtópico',
                'verbose_name_plural': 'vídeos de subtópicos',
            },
        ),
    ]
