# Generated by Django 6.0.6 on 2026-07-28 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trilhas', '0012_videosubtopico'),
    ]

    operations = [
        migrations.AddField(
            model_name='trilha',
            name='diamante_gasto',
            field=models.BooleanField(default=False, verbose_name='diamante gasto na criação'),
        ),
    ]
