# Generated by Django 6.0.6 on 2026-07-31 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trilhas', '0014_videonivel_delete_videosubtopico'),
    ]

    operations = [
        migrations.AddField(
            model_name='videonivel',
            name='etapa',
            field=models.CharField(blank=True, max_length=80, verbose_name='etapa atual'),
        ),
        migrations.AddField(
            model_name='videonivel',
            name='iniciado_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='início da geração'),
        ),
    ]
