# Generated by Django 6.0.8 on 2026-09-14 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trilhas', '0015_videonivel_etapa_videonivel_iniciado_em'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtopico',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
